#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-opencontainers-runtime-spec
Version  : b185d033e95cc06825f4fe2f631f31e0e43bf58b
Release  : 1
URL      : https://github.com/opencontainers/runtime-spec/archive/b185d033e95cc06825f4fe2f631f31e0e43bf58b.tar.gz
Source0  : https://github.com/opencontainers/runtime-spec/archive/b185d033e95cc06825f4fe2f631f31e0e43bf58b.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : go

%description
# Open Container Runtime Specification
The [Open Container Initiative](http://www.opencontainers.org/) develops specifications for standards on Operating System process and application containers.

%prep
%setup -q -n runtime-spec-b185d033e95cc06825f4fe2f631f31e0e43bf58b

%build

%install
gopath="/usr/lib/golang"
library_path="github.com/opencontainers/runtime-spec"
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     echo ${file}
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done


%files
%defattr(-,root,root,-)
/usr/lib/golang/src/github.com/opencontainers/runtime-spec/schema/validate.go
/usr/lib/golang/src/github.com/opencontainers/runtime-spec/specs-go/config.go
/usr/lib/golang/src/github.com/opencontainers/runtime-spec/specs-go/state.go
/usr/lib/golang/src/github.com/opencontainers/runtime-spec/specs-go/version.go
